### ISSUE TITLE
error in middleware of fulcro

### ISSUE THREAD

**Issue by bastiion** [multimodalrouting/osm-fulcro#6]
20-01-17 20:53:20 UnknownHost ERROR [com.fulcrologic.fulcro.server.api-middleware:71] - Parser threw an exception on nil
                                                 java.lang.Thread.run              Thread.java:  748
                   java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  624
                    java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1149
                                  java.util.concurrent.FutureTask.run          FutureTask.java:  266
                  java.util.concurrent.Executors$RunnableAdapter.call           Executors.java:  511
                                   org.httpkit.server.HttpHandler.run         RingHandler.java:  115
                                    ring.middleware.gzip/wrap-gzip/fn                 gzip.clj:  100
                                    ring.middleware.cors/wrap-cors/fn                cors.cljc:  205
                                     ring.middleware.cors/handle-cors                cors.cljc:  177
                                     ring.middleware.ssl/wrap-hsts/fn                  ssl.clj:  105
                           ring.middleware.x-headers/wrap-x-header/fn            x_headers.clj:   22 (repeats 2 times)
                    ring.middleware.not-modified/wrap-not-modified/fn         not_modified.clj:   61
              ring.middleware.default-charset/wrap-default-charset/fn      default_charset.clj:   31
                    ring.middleware.content-type/wrap-content-type/fn         content_type.clj:   34
           ring.middleware.resource/wrap-resource-prefer-resources/fn             resource.clj:   25
        ring.middleware.absolute-redirects/wrap-absolute-redirects/fn   absolute_redirects.clj:   47
                              ring.middleware.cookies/wrap-cookies/fn              cookies.clj:  175
                                ring.middleware.params/wrap-params/fn               params.clj:   67
            ring.middleware.multipart-params/wrap-multipart-params/fn     multipart_params.clj:  173
                  ring.middleware.nested-params/wrap-nested-params/fn        nested_params.clj:   89
                ring.middleware.keyword-params/wrap-keyword-params/fn       keyword_params.clj:   53
                              ring.middleware.session/wrap-session/fn              session.clj:  108
                 app.server-components.middleware/wrap-html-routes/fn           middleware.clj:   82
    com.fulcrologic.fulcro.server.api-middleware/wrap-transit-response/fn       api_middleware.clj:  166
    com.fulcrologic.fulcro.server.api-middleware/wrap-transit-params/fn       api_middleware.clj:  139
                       ring.middleware.file/wrap-file-prefer-files/fn                 file.clj:   38
                              ring.middleware.webjars/wrap-webjars/fn              webjars.clj:   41
                         app.server-components.middleware/wrap-api/fn           middleware.clj:   29
      com.fulcrologic.fulcro.server.api-middleware/handle-api-request       api_middleware.clj:   68
     com.fulcrologic.fulcro.server.api-middleware/handle-api-request/fn       api_middleware.clj:   69
                      app.server-components.middleware/wrap-api/fn/fn           middleware.clj:   31
             app.server-components.pathom/build-parser/wrapped-parser               pathom.clj:   95
                                               clojure.core.async/<!!                async.clj:  112
                      clojure.core.async.impl.protocols/eval3595/fn/G            protocols.clj:   15
                                      clojure.core/-cache-protocol-fn         core_deftype.clj:  583
      java.lang.IllegalArgumentException: No implementation of method: :take! of protocol: #'clojure.core.async.impl.protocols/ReadPort found for class: clojure.lang.PersistentArrayMap

Happens if iOS app tries to access the server via CORS

I tried JDK8 and JDK11

**Comment by bastiion** [comment]
caused by Access-Controll-Origin

Temporary fixed by checking for `nil` in pathom.cljs parser-builder

**Comment by johannesloetzsch** [comment]
@bastiion Can I close it?

**Comment by bastiion** [comment]
yes
